apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-configmap-{{.Chart.Version}}
data:
  port: "8080"
  {{- if eq .Values.env "dev" }}
  allowTesting: "true"
  {{- else }}
  allowTesting: "false"
  {{- end }}
