apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "api-al-adhan.fullname" . }}
  labels:
    app: {{ template "api-al-adhan.name" . }}
    chart: {{ template "api-al-adhan.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ template "api-al-adhan.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "api-al-adhan.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "api-al-adhan.serviceAccountName" . }}
      securityContext: {{ toYaml .Values.podSecurityContext | indent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080  # Ensure this matches the service port
              protocol: TCP
          envFrom:
            - secretRef:
                name: moonode-api-al-adhan-secret
          livenessProbe:
            httpGet:
              path: /status
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /status
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{ toYaml .Values.resources | indent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | indent 8 }}
      {{- end }}
