apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-al-adhan.fullname" . }}
  labels:
    {{- include "api-al-adhan.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080 
      protocol: TCP
      name: http
  selector:
    {{- include "api-al-adhan.selectorLabels" . | nindent 4 }}
